# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=140)),
                ('sex', models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=20, null=True)),
            ],
        ),
    ]
